"""Autogenerated verbs must come out fully translated (issue #59 follow-up).

autogenerate_missing_verb used a hand-kept per-language target table that left
Hebrew out and never translated the lemma, so generated Italian/French (and any
other) verbs lacked Hebrew example translations and every lemma translation
until someone ran the backfill tool. These tests run the real
translate_examples/translate_lemma and stub only the model calls, so they prove
what ends up in the stored verb.
"""

from __future__ import annotations

import asyncio
import concurrent.futures
from unittest.mock import AsyncMock, patch

import pytest

from core.languages.config import UI_LANGUAGES
from core.verb_autogen import autogenerate_missing_verb

_SENTENCE = "Una frase."
_PAYLOAD = {
    "lemma": "parlare",
    "morph": None,
    "forms": {"infinitive": "parlare"},
    "examples": [{"dst": _SENTENCE}],
}


def _fake_gemini(verb_lang, lemma, targets, sentences, project):
    return [{t: f"{t}:{s}" for t in targets} for s in sentences]


def _fake_claude(verb_lang, lemma, targets, sentences, api_key):
    return [{t: f"{t}:{s}" for t in targets} for s in sentences]


def _fake_gemini_lemma(verb_lang, lemma, targets, project):
    return {t: f"{t}:{lemma}" for t in targets}


def _fake_claude_lemma(verb_lang, lemma, targets, api_key):
    return {t: f"{t}:{lemma}" for t in targets}


def _run_async(coro):
    """Run a coroutine in a fresh worker-thread loop (see tests/test_session_tracker.py):
    Playwright e2e can leave a running loop in the main thread, which breaks a
    bare run_until_complete/asyncio.run there, and a fresh loop must be closed."""
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
        return pool.submit(asyncio.run, coro).result()


def _run_autogen(language: str, payload: dict, *, api_key="k", gemini=_fake_gemini):
    key_patch = (
        patch("core.verb_autogen._load_anthropic_api_key", return_value=api_key)
        if api_key is not None
        else patch("core.verb_autogen._load_anthropic_api_key", side_effect=RuntimeError("no key"))
    )
    with (
        patch("core.verb_autogen._generate_verb_payload", new=AsyncMock(return_value=payload)),
        patch("core.verb_autogen._get_max_rank", return_value=0),
        patch("app.routes.admin_candidates._warm_verb_audio", new=AsyncMock()),
        patch("core.translation_service._call_gemini", side_effect=gemini),
        patch("core.translation_service._call_claude", side_effect=_fake_claude),
        patch("core.translation_service._call_gemini_lemma", side_effect=_fake_gemini_lemma),
        patch("core.translation_service._call_claude_lemma", side_effect=_fake_claude_lemma),
        key_patch,
    ):
        _run_async(autogenerate_missing_verb(language=language, query=payload["lemma"], audio_backend=object()))


def _live_verb(fake_db, verb_id: str) -> dict:
    snapshot = fake_db.collection("verbs").document(verb_id).get()
    assert snapshot.exists, f"{verb_id} was not promoted"
    return snapshot.to_dict()


@pytest.mark.parametrize("language", ["it", "fr", "es", "en"])
def test_generated_verb_is_translated_into_every_other_ui_language(fake_db, language: str) -> None:
    payload = {**_PAYLOAD, "lemma": {"it": "parlare", "fr": "parler", "es": "hablar", "en": "speak"}[language]}
    _run_autogen(language, payload)

    verb = _live_verb(fake_db, f"{language}_{payload['lemma']}")
    expected_targets = {lang for lang in UI_LANGUAGES if lang != language}

    assert set(verb["examples"][0]["translations"]) == expected_targets
    assert set(verb["lemma_translations"]) == expected_targets


def test_translation_failure_never_blocks_promotion(fake_db) -> None:
    with (
        patch("core.translation_service._call_gemini", side_effect=RuntimeError("gemini down")),
        patch("core.translation_service._call_claude", side_effect=RuntimeError("claude down")),
        patch("core.translation_service._call_gemini_lemma", side_effect=RuntimeError("gemini down")),
        patch("core.translation_service._call_claude_lemma", side_effect=RuntimeError("claude down")),
    ):
        # Patched again inside _run_autogen; the outer patches make every model call fail.
        with (
            patch("core.verb_autogen._generate_verb_payload", new=AsyncMock(return_value=_PAYLOAD)),
            patch("core.verb_autogen._get_max_rank", return_value=0),
            patch("app.routes.admin_candidates._warm_verb_audio", new=AsyncMock()),
            patch("core.verb_autogen._load_anthropic_api_key", return_value="k"),
        ):
            _run_async(autogenerate_missing_verb(language="it", query="parlare", audio_backend=object()))

    verb = _live_verb(fake_db, "it_parlare")
    assert verb["forms"] == {"infinitive": "parlare"}
    assert "lemma_translations" not in verb
    assert "translations" not in verb["examples"][0]


def test_missing_anthropic_key_still_translates_non_hebrew_targets(fake_db) -> None:
    _run_autogen("it", _PAYLOAD, api_key=None)

    verb = _live_verb(fake_db, "it_parlare")
    assert {"en", "ru", "es"} <= set(verb["examples"][0]["translations"])
    assert {"en", "ru", "es"} <= set(verb["lemma_translations"])


def test_hung_translation_never_delays_publishing(fake_db, monkeypatch) -> None:
    import time

    monkeypatch.setattr("core.verb_autogen._TRANSLATION_TIMEOUT_SECONDS", 0.2)

    def slow_gemini(verb_lang, lemma, targets, sentences, project):
        time.sleep(1.0)
        return _fake_gemini(verb_lang, lemma, targets, sentences, project)

    started = time.monotonic()
    _run_autogen("it", _PAYLOAD, gemini=slow_gemini)
    elapsed = time.monotonic() - started

    verb = _live_verb(fake_db, "it_parlare")
    assert verb["forms"] == {"infinitive": "parlare"}
    assert "translations" not in verb["examples"][0]
    assert elapsed < 5
