"""ui_language propagation regression tests.

Firebase Hosting strips all cookies except __session before forwarding to
Cloud Run. ui_language was only stored as a cookie, so it was silently lost on
every navigation. The fix embeds ui_language as a URL query parameter in nav
links, form hidden inputs, and server-side redirect targets.

This file covers:
  - Nav links (Browse, Practice, bottom-nav tabs, board back link)
  - JS global (VB_UI_LANG injected into verbs page)
  - Home search form and language-selector onchange
  - Verbs page search form
  - /set_language redirect
  - /search_verb redirect (found and not-found paths)
"""

from __future__ import annotations

from fastapi.testclient import TestClient

from core.models import Board, VerbEntry


def _make_board(verb: VerbEntry) -> Board:
    return Board(
        language="en",
        verb=verb,
        voice_key="female",
        voice_label="Female",
        sections=[
            {
                "title": "Present",
                "rows": [
                    {
                        "key": "base",
                        "label": "Base",
                        "text": verb.forms.get("base", ""),
                        "href": "",
                    },
                ],
            }
        ],
    )


# ── nav links (Firebase Hosting cookie stripping) ──────────────────────────


def test_home_browse_link_includes_ui_language(client: TestClient) -> None:
    """Browse Verbs link on home page must carry ui_language so it survives
    Firebase Hosting's cookie stripping.
    """
    html = client.get("/?ui_language=ru&language=en").text
    assert "/verbs?language=en&ui_language=ru" in html


def test_home_practice_shortcut_includes_ui_language(client: TestClient) -> None:
    """Practice shortcut link on home page must carry ui_language."""
    html = client.get("/?ui_language=ru&language=en").text
    assert "/verbs?language=en&ui_language=ru#practice-panel" in html


def test_verbs_bottom_nav_search_tab_includes_ui_language(client: TestClient, monkeypatch) -> None:
    """Bottom-nav Search tab on verbs page must carry ui_language.

    Jinja2 autoescape is active for HTML templates, so & is rendered as &amp;
    inside href attributes generated by the template include.
    """
    monkeypatch.setattr("app.routes.verbs.load_entries_for_language", lambda **kw: [])
    html = client.get("/verbs?language=en&ui_language=ru").text
    assert "/?language=en&amp;ui_language=ru" in html


def test_verbs_bottom_nav_list_tab_includes_ui_language(client: TestClient, monkeypatch) -> None:
    """Bottom-nav List tab on verbs page must carry ui_language."""
    monkeypatch.setattr("app.routes.verbs.load_entries_for_language", lambda **kw: [])
    html = client.get("/verbs?language=en&ui_language=ru").text
    assert "/verbs?language=en&amp;ui_language=ru" in html


def test_verbs_page_exposes_vb_ui_lang_global(client: TestClient, monkeypatch) -> None:
    """verbs.html must embed window.VB_UI_LANG so JS can build learn links with
    the correct ui_language parameter.
    """
    monkeypatch.setattr("app.routes.verbs.load_entries_for_language", lambda **kw: [])
    html = client.get("/verbs?language=en&ui_language=ru").text
    assert 'window.VB_UI_LANG = "ru"' in html


def test_board_bottom_nav_back_href_includes_ui_language(
    mock_verb: VerbEntry,
) -> None:
    """Board bottom-nav back link must include ui_language so navigating back to
    the verbs list preserves the UI locale.

    render_board_html uses a Jinja2 environment with autoescape, so & in href
    attributes is rendered as &amp;.
    """
    from core.render import render_board_html

    html = render_board_html(_make_board(mock_verb), ui_lang="ru")
    assert "/verbs?language=en&amp;ui_language=ru" in html


# ── /set_language redirect ─────────────────────────────────────────────────


def test_set_language_preserves_ui_language(client: TestClient) -> None:
    """/set_language redirect must forward ui_language to home."""
    resp = client.get("/set_language?language=he&ui_language=ru", follow_redirects=False)
    assert resp.status_code in (301, 302, 303, 307, 308)
    assert "ui_language=ru" in resp.headers["location"]
    assert "language=he" in resp.headers["location"]


def test_set_language_without_ui_language(client: TestClient) -> None:
    """/set_language with no ui_language must still redirect to home cleanly."""
    resp = client.get("/set_language?language=ru", follow_redirects=False)
    assert resp.status_code in (301, 302, 303, 307, 308)
    assert "language=ru" in resp.headers["location"]
    assert "ui_language" not in resp.headers["location"]


# ── /search_verb redirect ──────────────────────────────────────────────────


def test_search_verb_found_preserves_ui_language(client: TestClient, monkeypatch) -> None:
    """/search_verb redirect to /learn must carry ui_language."""
    monkeypatch.setattr(
        "app.routes.home.find_verb_by_search_extract",
        lambda lang, query: {"verb_id": "en_go"},
    )
    resp = client.get("/search_verb?language=en&q=go&ui_language=ru", follow_redirects=False)
    assert resp.status_code in (301, 302, 303, 307, 308)
    assert "ui_language=ru" in resp.headers["location"]
    assert "verb_id=en_go" in resp.headers["location"]


def test_search_verb_not_found_preserves_ui_language(client: TestClient, monkeypatch) -> None:
    """/search_verb not-found redirect must carry ui_language."""
    monkeypatch.setattr("app.routes.home.find_verb_by_search_extract", lambda lang, query: None)
    monkeypatch.setattr("app.routes.home.find_best_entry", lambda entries, query: None)
    monkeypatch.setattr("app.routes.home._load_entries", lambda lang: [])
    monkeypatch.setattr("app.routes.home.log_missing_verb_search", lambda **kw: None)
    resp = client.get("/search_verb?language=en&q=xyz&ui_language=ru", follow_redirects=False)
    assert resp.status_code in (301, 302, 303, 307, 308)
    assert "ui_language=ru" in resp.headers["location"]


# ── form hidden inputs ─────────────────────────────────────────────────────


def test_home_carries_ui_language(client: TestClient) -> None:
    """Home page links (browse, about, feedback) must carry ui_language=ru."""
    html = client.get("/?ui_language=ru&language=en").text
    # Browse link and practice link carry ui_language
    assert "ui_language=ru" in html
    # Language select onchange URL carries ui_language
    assert "ui_language=ru" in html


def test_home_language_select_onchange_carries_ui_language(
    client: TestClient,
) -> None:
    """Language selector onchange must include ui_language in the /set_language URL."""
    html = client.get("/?ui_language=ru&language=en").text
    assert "set_language" in html
    assert "ui_language=ru" in html


def test_verbs_search_form_carries_ui_language(client: TestClient, monkeypatch) -> None:
    """Verbs page search form must include hidden ui_language and return_to with ui_language."""
    monkeypatch.setattr("app.routes.verbs.load_entries_for_language", lambda **kw: [])
    html = client.get("/verbs?language=en&ui_language=ru").text
    assert 'name="ui_language"' in html
    assert 'value="ru"' in html
    assert "return_to" in html
    assert "ui_language=ru" in html
